# Generated by Django 4.2.3 on 2023-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(default=1, max_length=50),
        ),
    ]
