# Generated by Django 4.2.3 on 2023-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=2500)),
                ("address", models.CharField(max_length=250)),
                ("tenant_name", models.CharField(max_length=50)),
                ("tenant_phone", models.CharField(max_length=15)),
                ("landlord_name", models.CharField(max_length=50)),
                ("landlord_phone", models.CharField(max_length=15)),
                ("rent", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "home",
            },
        ),
    ]
