# Generated by Django 4.2.3 on 2023-07-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="landlord_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlord_user",
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="home",
            name="tenant_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_user",
                to="authentication.user",
            ),
        ),
    ]
