# Generated by Django 4.2.3 on 2023-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_home_landlord_user_home_tenant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="images",
            field=models.JSONField(default=dict),
        ),
    ]
