# Generated by Django 4.2.3 on 2023-08-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_home_last_payment_alter_home_rent_due"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="last_payment",
        ),
        migrations.RemoveField(
            model_name="home",
            name="rent_due",
        ),
    ]
